### ISSUE TITLE
App crashing on Android 10.

### ISSUE THREAD

**Issue by Harishwarrior** [praveenkumar-programmer/Counter-App-Simple-MVVM-Example#2]
The app crashes on launching. Will update the issue with log soon.

**Comment by praveenkumar-programmer** [comment]
Kindly leave the log data.. and also did u install the apk downloaded from releases section or did u compiled on ur own?

**Comment by Harishwarrior** [comment]
I have tried the apk from the release build also. 

Here's the log


2021-03-22 22:28:03.474 10791-10791/com.geeks4ever.counter_app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.geeks4ever.counter_app, PID: 10791
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.geeks4ever.counter_app.viewmodel.CounterViewModel$1.onChanged(CounterViewModel.java:39)
        at com.geeks4ever.counter_app.viewmodel.CounterViewModel$1.onChanged(CounterViewModel.java:36)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by praveenkumar-programmer** [comment]
The problems are resolved @Harishwarrior ..
=> The crashing issue was because of not doing a null check in the viewmodel before trying to fetch the value.
=> The No action on clicking any buttons is because of using update query instead of using insert query in the DAO of room database and hence the app tried to update a value which not yet written causing the no action,

Thanks a lots to @Harishwarrior  for bringing up the bugs.. keep rocking ;)
